# Settings for the niri shell, shipped as ~/.config/quickshell/settings.json
# (generated by modules/home/dotfiles/default.nix). Edit here and rebuild;
# the shell has no runtime settings UI on purpose.
{ laptop ? false }:

{
  appearance = {
    accent = "#3daee9";        # Breeze blue
    accentFromWallpaper = false;   # true: derive the accent from the wallpaper instead
    panelOpacity = 0.95;       # 0..1, bar and popups
    barHeight = 36;
    radius = 4;
    font = "JetBrainsMono Nerd Font";
    fontSize = 10;
    reducedMotion = "auto";    # true | false | "auto": off on AC, on while running on battery
  };

  bar = {
    # right-side widgets, in display order; set to false to hide
    tray = true;
    layout = true;
    volume = true;
    bluetooth = true;
    battery = true;
    cpu = true;
    memory = true;
    temps = true;
    disk = true;
    network = true;
    notifications = true;
    control = true;
    sidebar = true;
    # centre
    nowPlaying = true;
    windowTitle = true;        # focused window icon + title next to the workspaces
    workspaceIcons = true;     # app icons inside the workspace pills
    marqueeWidth = 220;
    clockFormat = "HH:mm";
    dateFormat = "ddd d MMM";
  };

  # desktop ids shown in the sidebar's quick launch
  pinned = [
    "org.kde.dolphin" "zen-beta" "code" "dev.zed.Zed" "discord"
    "moe.kopuz.kopuz" "com.mitchellh.ghostty" "steam" "thunderbird" "org.jellyfin.JellyfinDesktop"
  ];

  weather = { city = "Istanbul"; };

  dashboard = { visualizer = !laptop; };   # cava bars in the media card (runs only while it is open)

  osd = { timeoutMs = 1500; bottomMargin = 90; };

  idle = {
    ac = if laptop
      then { dim = 300; lock = 600; screenOff = 630; suspend = 0; }
      else { dim = 0; lock = 900; screenOff = 960; suspend = 0; };
    battery = { dim = 120; lock = 240; screenOff = 270; suspend = 900; };
    lockedScreenOff = 30;
  };

  notifications = { timeoutMs = 6000; maxPopups = 5; };

  wallpaper = "";              # empty = the one shipped in the repo
}
