#!/usr/bin/env sh

yabai -m config external_bar all:40:0

yabai -m config layout                       bsp
yabai -m config window_placement             second_child

yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_follows_focus          on

yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m rule --add app="^System Settings$"  manage=off
yabai -m rule --add app="^Calculator$"       manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
