[general]
bars = 40
framerate = 30
autosens = 1
sensitivity = 100
lower_cutoff_freq = 40
higher_cutoff_freq = 12000

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59

[smoothing]
noise_reduction = 60
